apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-feed
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: lijkal/udagram-api-feed:v1
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: "200Mi"
            requests:
              cpu: 200m
              memory: "100Mi"       
          envFrom:
            # Define the environment variable
            - configMapRef:
                    name: env-configmap
            - secretRef:
                    name: env-secret
            - secretRef:
                    name: aws-secret