apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec: 
  replicas: 2
  selector:
    matchLabels: 
      run: frontend
  template:
    metadata:
      labels: 
        run: frontend
    spec:
      containers:
      - name: frontend
        image: lijkal/udagram-frontend:v33
        ports:
        - containerPort: 80
        # resources:
        #   limits:
        #     cpu: 200m
        #   requests:
        #     cpu: 500m



